# This is a basic workflow to help you get started with Actions

name: CI DC

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            mmartinsti/rotten-potatoes:latest
            mmartinsti/rotten-potatoes:${{ github.run_number }}

# Agora vamos ao processo de CD

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v2.1
        with:
          resource-group: rg_tf-kubernets
          cluster-name: live-cluster2
          
      
      
          
          
